# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-01 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postorius', '0003_drop_addressconfirmationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscriberStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('channel', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
