# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postorius', '0003_drop_addressconfirmationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssaySubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=100)),
                ('link', models.CharField(default=None, max_length=100)),
                ('is_woman', models.BooleanField(default=False)),
                ('is_woman_in_tech', models.BooleanField(default=False)),
                ('essay', models.CharField(max_length=800)),
                ('accepted_terms', models.BooleanField(default=1)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
