# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postorius', '0004_essaysubscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaysubscribe',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
